### ISSUE TITLE
Using an existing NATS connection

### ISSUE THREAD

**Issue by tr11** [nats-io/graft#36]
Currently the `NewNatsRpc` func creates a new `NatsRpcDriver` using a `*nats.Options` parameter.  We already have a NATS connection in our app and were thinking about reusing it here instead of having the driver create a new connection. Is there a reason why we shouldn't reuse the connection and, if not, would you consider adding a new method to create a `NatsRpcDriver` from an existing `*nc.Conn`?

**Comment by derekcollison** [comment]
You are welcome to submit a PR. We are not actively adding anything to this repo and usually move people to look at JetStream K/V and CAS operations.

Looping in @ripienaar

**Comment by tr11** [comment]
Thanks, PR is above. 

I didn't think about using JS -- all we really needed was a system for leader election, so this library seemed appropriate. Is there a better way to do the same within JetStream?

**Comment by derekcollison** [comment]
Will let @ripienaar weigh in on how he suggests folks use CAS and KV to accomplish this.

**Comment by ripienaar** [comment]
The benefits of using JetStream for this is that your applications become a lot simpler - big benefit if you have many apps of course.

With a 3 node JetStream cluster handling the raft you can outsource this function to its raft layer rather than have a raft layer in every single application.  It also means you can auto scale your app without raft problems (something thats quite hard to do with RAFT systems) and other similar benefits.

The process is basically:

```
forever
   try to Create() a key
   if you can create it
     sleep for a cool down around 1.5 times bucket TTL
     You become leader
```

The leader maintains leadership using:

```
forever 
   try to Update() the key on a short interval
      if Update() fails
          you lost leadership
```

This works pretty well and has similar guarantees to other comparible systems like those built using kubernetes resources etc. ie. small % chance of 2 leaders active at a time and your failover and failure detection periods is a function of the bucket TTL.
